[package]
name = "rivals_mod_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
hex = "0.4.3"
repak-rivals = { path = "./repak-rivals/repak_rivals" ,features = ["oodle_implicit_dynamic"]}